<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Entorn.Scanner.Contracts" />
    <ProjectReference Include="../Archie.Contracts/Archie.Contracts.csproj" />
    <Using Include="Entorn.Scanner.Contracts" />
  </ItemGroup>
</Project>
